apiVersion: batch/v1
kind: Job
metadata:
  name: db-ckeck-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check
          image: busybox
          command:
            - /bin/sh
            - -c
            - "echo 'Running DB check to $DB_HOST...'; sleep 10; echo 'Connected!'"
          env:
            - name: DB_HOST
              valueFromKeyRef:
                name: db-config
                key: db_host
