apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Define el orden de sincronización en ArgoCD.
    # Los recursos con menor valor se aplican primero.
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - /bin/sh
            - -c
            - "echo 'Running DB migration...'; sleep 10; echo 'Done'"
